#!/bin/sh

uci set luci.main.lang=zh_cn
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci delete system.ntp.server
uci add_list system.ntp.server='ntp.tencent.com'
uci add_list system.ntp.server='ntp1.aliyun.com'
uci add_list system.ntp.server='ntp.ntsc.ac.cn'
uci add_list system.ntp.server='cn.ntp.org.cn'
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

#关闭 IPv6
#uci delete network.globals.ula_prefix
#uci delete network.lan.ip6assign
#uci delete network.wan6
#uci delete dhcp.lan.ra
#uci delete dhcp.lan.ra_management
#uci delete dhcp.lan.dhcpv6
#uci delete dhcp.lan.ndp
#uci commit dhcp


ln -sf /sbin/ip /usr/bin/ip


sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh


[ ! -f '/usr/bin/ip' ] && [ -f '/sbin/ip' ] && ln -sf /sbin/ip /usr/bin/ip
[ ! -f '/usr/bin/wget-ssl' ] && [ -f '/usr/bin/wget' ] && ln -sf /usr/bin/wget /usr/bin/wget-ssl


sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf


rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache


exit 0
