#!/bin/sh

touch /etc/crontabs/root

chmod -R 0775 /etc/init.d /usr/share

if [[ `grep -c "x86_64" /etc/openwrt_release` -eq '0' ]]; then
  export DISTRIB_TA="$(grep DISTRIB_TARGET= /etc/openwrt_release |sed "s/'//g" |cut -d "=" -f2)"
  sed -i "s?x86_64?${DISTRIB_TA}?g" /etc/banner
fi

if [[ `grep -c "danshui" /etc/opkg/distfeeds.conf` -ge '1' ]]; then
  sed -i '/danshui/d' /etc/opkg/distfeeds.conf
fi
if [[ `grep -c "helloworld" /etc/opkg/distfeeds.conf` -ge '1' ]]; then
  sed -i '/helloworld/d' /etc/opkg/distfeeds.conf
fi
if [[ `grep -c "passwall" /etc/opkg/distfeeds.conf` -ge '1' ]]; then
  sed -i '/passwall/d' /etc/opkg/distfeeds.conf
fi

sed -i 's/distversion)%>/distversion)%><!--/g' /usr/lib/lua/luci/view/admin_status/index.htm
sed -i 's/luciversion)%>)/luciversion)%>)-->/g' /usr/lib/lua/luci/view/admin_status/index.htm
sed -i 's#localtime  = .*#localtime  = os.date("%Y-%m-%d") .. " " .. os.date("%X") .. " " .. translate(os.date("%A")),#g' /usr/lib/lua/luci/view/admin_status/index.htm


exit 0
