#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=99

run_zzz_default() {
    
	if [ -f "/etc/default-setting" ]; then
		/etc/default-setting
                rm -rf /etc/default-setting
	fi
	
	if [[ `grep -c "openwrt -e" "/etc/rc.local"` -eq '0' ]]; then
		sed -i "/exit 0/i\openwrt -e" "/etc/rc.local"
	fi
}

start() {
	run_zzz_default
}
