#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=90

Postapp()
{
    if [ -f "/etc/zzz-default-settings" ]; then
      /etc/zzz-default-settings
      rm -rf /etc/zzz-default-settings
    fi
    
    if [ -f "/etc/default-setting" ]; then
      /etc/default-setting
      rm -rf /etc/default-setting
      reboot -f
    fi
}

start() {
    Postapp
}
