#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=99

zzz_default() {
	
	if [ -f "/etc/zzz-default-settings" ]; then
		/etc/zzz-default-settings
                rm -rf /etc/zzz-default-settings
	fi
    
	if [ -f "/etc/default-setting" ]; then
		/etc/default-setting
		uci commit network
		uci commit luci
		uci commit dhcp
		uci commit system
		uci commit firewall
		if [ -f /etc/config/ttyd ]; then
		        uci commit ttyd
		fi
                rm -rf /etc/default-setting
	fi
	
	if [[ -f '/mnt/network' ]]; then
		cp -Rf /mnt/network /etc/config/network
		uci commit network
		rm -rf /mnt/network
	fi
	
	if [[ `grep -c "/tmp/luci-\*cache\*" /etc/crontabs/root` -eq '0' ]]; then
		echo "0 1 * * 1 rm -rf /tmp/luci-*cache* > /dev/null 2>&1" >> /etc/crontabs/root
		/etc/init.d/cron restart
	fi
	
	if [[ `grep -c "Detectionnetwork" /etc/crontabs/root` -ge '1' ]]; then
		if [[ ! -f '/mnt/Detectionnetwork' ]]; then
			sed -i '/Detectionnetwork/d' /etc/crontabs/root
		fi
	fi
	
	rm -rf /tmp/luci-*cache*
        /etc/init.d/network restart
	/etc/init.d/uhttpd restart
	/etc/init.d/dnsmasq restart
	/etc/init.d/firewall restart
	exit 0

}

start() {
	zzz_default
}
